name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - uses: actions/setup-go@v5
      with:
        go-version: stable

    - name: golangci-lint
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60

    - name: Install dependencies
      run: go mod tidy

    - name: Run tests
      run: go test ./...